name: "HCL AppScan CodeSweep"

on:
  push:
    branches:
      - development
    paths:
      - "**/*.js"

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run AppScan CodeSweep
        uses: HCL-TECH-SOFTWARE/appscan-codesweep-action@v2.1
        with:
          scan-type: "full"
          code-sweep-target: "."